# Generated by Django 3.1.1 on 2020-09-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='size_d',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='size_h',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='size_w',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
