# Generated by Django 3.1.1 on 2020-09-16 06:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('category', '0002_auto_20200916_0656'),
        ('article', '0003_articlegroup'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
