# Generated by Django 3.1.1 on 2020-09-16 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('article', '0004_auto_20200916_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='article.articlegroup'),
        ),
    ]
