# Generated by Django 3.1.1 on 2020-09-16 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contragent', '0001_initial'),
        ('measure', '0001_initial'),
        ('article', '0005_auto_20200916_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='supplier',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='contragent.contragent',
                                    verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='article',
            name='unit_m',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='measure.measure',
                                    verbose_name='Ед.изм.'),
        ),
        migrations.AddField(
            model_name='articlegroup',
            name='parrent',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='article.articlegroup',
                                    verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='article.articlegroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/goods/',
                                    verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='size_d',
            field=models.PositiveIntegerField(blank=True, null=True,
                                              verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='article',
            name='size_h',
            field=models.PositiveIntegerField(blank=True, null=True,
                                              verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='article',
            name='size_w',
            field=models.PositiveIntegerField(blank=True, null=True,
                                              verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='article',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True,
                                              verbose_name='Масса'),
        ),
    ]
