# Generated by Django 3.1.1 on 2020-09-29 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('article', '0007_auto_20200916_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlegroup',
            old_name='parrent',
            new_name='parent',
        ),
    ]
