# Generated by Django 3.1.1 on 2020-09-16 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('invoice', '0002_auto_20200916_2152'),
        ('article', '0006_auto_20200916_2152'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('oper_date', models.DateTimeField(db_index=True,
                                                   verbose_name='Дата операции')),
                ('status', models.CharField(
                    choices=[('buy', 'Покупка'), ('sell', 'Продажа'),
                             ('off', 'Списание')], db_index=True,
                    max_length=10, verbose_name='Вид операции')),
                ('quantity',
                 models.DecimalField(decimal_places=3, max_digits=19,
                                     verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19,
                                              verbose_name='Цена')),
                ('discont',
                 models.DecimalField(decimal_places=2, max_digits=19,
                                     verbose_name='Скидка')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=19,
                                              verbose_name='Сумма')),
                ('invoice',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   to='invoice.invoice',
                                   verbose_name='Накладная')),
                ('product',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   to='article.article',
                                   verbose_name='Номенклатура')),
                ('stock',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   to='stock.stock', verbose_name='Склад')),
            ],
        ),
    ]
