# Generated by Django 3.1.1 on 2020-09-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('title',
                 models.CharField(db_index=True, max_length=8, unique=True,
                                  verbose_name='Наименование')),
                ('description',
                 models.CharField(max_length=64, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
    ]
