# Generated by Django 3.1.1 on 2020-09-16 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contragent', '0001_initial'),
        ('article', '0003_articlegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('number',
                 models.CharField(max_length=32, verbose_name='Номер')),
                ('invoice_date', models.DateField(verbose_name='Дата')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=19,
                                              verbose_name='Сумма')),
                ('stock',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   to='stock.stock', verbose_name='Склад')),
                ('supplier',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   to='contragent.contragent',
                                   verbose_name='Поставщик')),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.PROTECT,
                    to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Накладная',
                'verbose_name_plural': 'Накладные',
                'ordering': ('invoice_date', 'supplier'),
            },
        ),
        migrations.CreateModel(
            name='InvoiceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('quantity',
                 models.DecimalField(decimal_places=3, max_digits=19,
                                     verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19,
                                              verbose_name='Цена')),
                ('invoice',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   to='invoice.invoice',
                                   verbose_name='Документ')),
                ('product',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   to='article.articles',
                                   verbose_name='Номенклатура')),
            ],
        ),
    ]
