# Generated by Django 3.1.1 on 2020-10-17 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('measure', '0001_initial'),
        ('invoice', '0002_auto_20200916_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetable',
            name='mesure',
            field=models.ForeignKey(default=1,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='measure.measure',
                                    verbose_name='Ед.изм.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(
                choices=[('buy', 'Покупка'), ('sell', 'Продажа'),
                         ('off', 'Списание'), ('return', 'Возврат'),
                         ('inventory', 'Инвентаризация')], db_index=True,
                max_length=10, verbose_name='Вид операции'),
        ),
        migrations.AlterField(
            model_name='invoicetable',
            name='invoice',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='invoice.invoice', verbose_name='Документ'),
        ),
    ]
